import type {
  BonixAssetDefinition,
  BuildingSlot,
  WorldBuildingData,
} from "@/types/3d";

// Initial mock data per PRD §85. Replaces the hard-coded arrays
// inside app/user/[userId]/city/page.tsx with shapes that match
// the planned Supabase schema (026_3d_world_engine.sql).

export const MOCK_WORLD = {
  id: "world-mock-1",
  name: "My City",
  level: 1,
  theme: "NIGHT" as const,
  maxSlots: 10,
};

export const MOCK_ASSETS: Record<string, BonixAssetDefinition> = {
  "asset-restaurant": {
    id: "asset-restaurant",
    url: "/3d/restaurant.glb",
    category: "RESTAURANT",
    assetType: "BUILDING",
    metadata: { polycount: 4200, supports_color: true, supports_logo: true },
  },
  "asset-cafe": {
    id: "asset-cafe",
    url: "/3d/cafe.glb",
    category: "CAFE",
    assetType: "BUILDING",
    metadata: { polycount: 3800, supports_color: true, supports_logo: true },
  },
  "asset-house": {
    id: "asset-house",
    url: "/3d/house.glb",
    category: "RESTAURANT",
    assetType: "BUILDING",
    metadata: { polycount: 3500, supports_color: true, supports_logo: true },
  },
  "asset-fitness": {
    id: "asset-fitness",
    url: "/3d/house.glb",
    category: "FITNESS",
    assetType: "BUILDING",
    metadata: { polycount: 3500, supports_color: true, supports_logo: true },
  },
  "asset-hotel": {
    id: "asset-hotel",
    url: "/3d/house.glb",
    category: "HOTEL",
    assetType: "BUILDING",
    metadata: { polycount: 3500, supports_color: true, supports_logo: true },
  },
  "asset-tree": {
    id: "asset-tree",
    url: "/3d/tree.glb",
    category: "VEGETATION",
    assetType: "VEGETATION",
    metadata: { polycount: 1200 },
  },
  "asset-lamp": {
    id: "asset-lamp",
    url: "/3d/lamp.glb",
    category: "PROP",
    assetType: "PROP",
    metadata: { polycount: 800 },
  },
};

export const MOCK_SLOTS: BuildingSlot[] = [
  {
    id: "slot-1",
    slotKey: "A-01",
    position: [-3.5, 0, 1.5],
    rotationY: 0.3,
    scale: 1,
    slotType: "RESTAURANT",
    occupied: true,
  },
  {
    id: "slot-2",
    slotKey: "A-02",
    position: [2.5, 0, 1.5],
    rotationY: -0.3,
    scale: 1,
    slotType: "CAFE",
    occupied: true,
  },
  {
    id: "slot-3",
    slotKey: "B-01",
    position: [4.2, 0, -2.2],
    rotationY: Math.PI - 0.4,
    scale: 1,
    slotType: "RESTAURANT",
    occupied: true,
  },
  {
    id: "slot-4",
    slotKey: "B-02",
    position: [-4.2, 0, -2.2],
    rotationY: Math.PI + 0.3,
    scale: 1,
    slotType: "FITNESS",
    occupied: true,
  },
  {
    id: "slot-5",
    slotKey: "C-01",
    position: [-1.2, 0, -4.5],
    rotationY: Math.PI,
    scale: 1,
    slotType: "HOTEL",
    occupied: true,
  },
  // Empty slots
  {
    id: "slot-6",
    slotKey: "A-03",
    position: [-1.2, 0, 4.2],
    rotationY: 0,
    scale: 1,
    slotType: "ANY",
    occupied: false,
  },
  {
    id: "slot-7",
    slotKey: "B-03",
    position: [1.2, 0, 4.2],
    rotationY: 0,
    scale: 1,
    slotType: "ANY",
    occupied: false,
  },
  {
    id: "slot-8",
    slotKey: "C-02",
    position: [0, 0, 1.5],
    rotationY: 0,
    scale: 1,
    slotType: "ANY",
    occupied: false,
  },
  {
    id: "slot-9",
    slotKey: "C-03",
    position: [0, 0, -4.5],
    rotationY: Math.PI,
    scale: 1,
    slotType: "ANY",
    occupied: false,
  },
];

export const MOCK_BUILDINGS: WorldBuildingData[] = [
  {
    id: "building-1",
    merchantId: "merchant-cocina-verde",
    merchantName: "La Cocina Verde",
    templateId: "tpl-restaurant-modern",
    assetId: "asset-restaurant",
    hasActivePromo: true,
    promoLabel: "20% OFF",
    promoId: "promo-cocina-1",
    isFavorite: true,
    isReserved: false,
    isNew: false,
    primaryColor: "#15803D",
    secondaryColor: "#F8FAFC",
    signText: "LA COCINA VERDE",
    level: 3,
    slotId: "slot-1",
  },
  {
    id: "building-2",
    merchantId: "merchant-montevideo-brew",
    merchantName: "Montevideo Brew",
    templateId: "tpl-cafe-modern",
    assetId: "asset-cafe",
    hasActivePromo: true,
    promoLabel: "2x Credits",
    promoId: "promo-brew-1",
    isFavorite: true,
    isReserved: false,
    isNew: false,
    primaryColor: "#B45309",
    secondaryColor: "#FFFBEB",
    signText: "MVDEO BREW",
    level: 2,
    slotId: "slot-2",
  },
  {
    id: "building-3",
    merchantId: "merchant-casa-nomada",
    merchantName: "Casa Nómada",
    templateId: "tpl-restaurant-rustic",
    assetId: "asset-house",
    hasActivePromo: false,
    isFavorite: true,
    isReserved: false,
    isNew: true,
    primaryColor: "#7C3AED",
    secondaryColor: "#FAF5FF",
    signText: "CASA NÓMADA",
    level: 2,
    slotId: "slot-3",
  },
  {
    id: "building-4",
    merchantId: "merchant-barrio-fitness",
    merchantName: "Barrio Fitness",
    templateId: "tpl-fitness-modern",
    assetId: "asset-fitness",
    hasActivePromo: false,
    isFavorite: true,
    isReserved: true,
    isNew: false,
    primaryColor: "#0EA5E9",
    secondaryColor: "#F0F9FF",
    signText: "BARRIO FITNESS",
    level: 1,
    slotId: "slot-4",
  },
  {
    id: "building-5",
    merchantId: "merchant-hotel-rambla",
    merchantName: "Hotel Rambla",
    templateId: "tpl-hotel-modern",
    assetId: "asset-hotel",
    hasActivePromo: false,
    isFavorite: true,
    isReserved: false,
    isNew: false,
    primaryColor: "#475569",
    secondaryColor: "#F8FAFC",
    signText: "HOTEL RAMBLA",
    level: 4,
    slotId: "slot-5",
  },
];
